server:
  port: 7071

use:
  datasource: master


spring:
  datasource:
    druid:
      initial-size: 3
      max-active: 5
      min-idle: 1
      max-wait: 60000
      master:
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&amp&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: ffcs_rp
      slave:
        url: jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: scott
        password: 1234




